version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.web
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend
